// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace TechShopBackendDotnet.Models;

[Table("cart_detail")]
[Index("CartId", Name = "FK_cart_detail_CART_ID")]
[Index("ProductId", Name = "FK_cart_detail_PRODUCT_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class CartDetail
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("CART_ID")]
    public int CartId { get; set; }

    [Column("PRODUCT_ID")]
    [JsonProperty("product_id")]
    public int ProductId { get; set; }

    [Required]
    [Column("COLOR")]
    [StringLength(255)]
    public string Color { get; set; }

    [Column("QUANTITY")]
    public int Quantity { get; set; }
}