// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("cart")]
[Index("CustomerEmail", Name = "FK_cart_CUSTOMER_EMAIL")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class Cart
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("CUSTOMER_EMAIL")]
    public string CustomerEmail { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }
}