// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("category")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class Category
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(50)]
    public string Name { get; set; }

}