// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("discount")]
public partial class Discount
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("CODE")]
    [StringLength(50)]
    public string Code { get; set; }

    [Required]
    [Column("TYPE")]
    [StringLength(20)]
    public string Type { get; set; }

    [Column("VALUE")]
    public double Value { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(255)]
    public string Description { get; set; }

    [Column("START_DATE")]
    public DateOnly? StartDate { get; set; }

    [Column("END_DATE")]
    public DateOnly? EndDate { get; set; }

    [Column("MIN_APPLY")]
    public double MinApply { get; set; }

    [Column("MAX_SPEED")]
    public double MaxSpeed { get; set; }

    [Column("QUANTITY")]
    public int Quantity { get; set; }

    [Required]
    [Column("STATUS")]
    [StringLength(20)]
    public string Status { get; set; }

    [Column("CREATED_AT")]
    public DateOnly CreatedAt { get; set; }

    [Column("UPDATED_AT")]
    public DateOnly? UpdatedAt { get; set; }

    [Column("DISABLED_AT")]
    public DateOnly? DisabledAt { get; set; }

}