// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("image_detail")]
[Index("ProductId", Name = "FK_image_detail_PRODUCT_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class ImageDetail
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Required]
    [Column("COLOR")]
    [StringLength(255)]
    public string Color { get; set; }

    [Column("ORDINAL")]
    public int Ordinal { get; set; }

    [Required]
    [Column("IMAGE", TypeName = "mediumblob")]
    public byte[] Image { get; set; }
}