// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace TechShopBackendDotnet.Models;

[Table("orders")]
[Index("DiscountId", Name = "FK_discount_id_orders")]
[Index("CustomerEmail", Name = "FK_orders_CUSTOMER_EMAIL")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class Order
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("CUSTOMER_EMAIL")]
    public string CustomerEmail { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("ADDRESS")]
    [StringLength(255)]
    public string Address { get; set; }

    [Required]
    [Column("WARD")]
    [StringLength(255)]
    public string Ward { get; set; }

    [Required]
    [Column("DISTRICT")]
    [StringLength(255)]
    public string District { get; set; }

    [Required]
    [Column("CITY")]
    [StringLength(255)]
    public string City { get; set; }

    [Required]
    [Column("PHONE")]
    [StringLength(255)]
    public string Phone { get; set; }

    [Column("DISCOUNT_ID")]
    public int? DiscountId { get; set; }

    [Column("SHIPPING_FEE")]
    public double ShippingFee { get; set; }

    [Column("TOTAL_PRICE")]
    public double TotalPrice { get; set; }

    [Column("NOTE", TypeName = "text")]
    public string Note { get; set; }

    [Column("ORDER_DATE")]
    public DateOnly OrderDate { get; set; }

    [Column("CANCELED_DATE")]
    public DateOnly? CanceledDate { get; set; }

    [Column("COMPLETED_DATE")]
    public DateOnly? CompletedDate { get; set; }

    [Required]
    [Column("DELIVERY_TYPE")]
    [StringLength(255)]
    public string DeliveryType { get; set; }

    [Required]
    [Column("PAYMENT_TYPE")]
    [StringLength(255)]
    public string PaymentType { get; set; }

    [Required]
    [Column("STATUS")]
    [StringLength(255)]
    public string Status { get; set; }


    
}