// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("order_detail")]
[Index("OrderId", Name = "FK_order_detail_ORDER_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class OrderDetail
{
    [Key] [Column("ID")] public int Id { get; set; }

    [Column("ORDER_ID")] public int OrderId { get; set; }

    [Column("PRODUCT_ID")] public int ProductId { get; set; }

    [Required]
    [Column("COLOR")]
    [StringLength(255)]
    public string Color { get; set; }

    [Column("QUANTITY")] public int Quantity { get; set; }

    [Column("PRICE")] public double Price { get; set; }
}
