// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("parameter_phone")]
[Index("ProductId", Name = "FK_parameter_phone_PRODUCT_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class ParameterPhone
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Required]
    [Column("SCREEN")]
    [StringLength(255)]
    public string Screen { get; set; }

    [Required]
    [Column("OPERATING_SYSTEM")]
    [StringLength(255)]
    public string OperatingSystem { get; set; }

    [Required]
    [Column("BACK_CAMERA")]
    [StringLength(255)]
    public string BackCamera { get; set; }

    [Required]
    [Column("FRONT_CAMERA")]
    [StringLength(255)]
    public string FrontCamera { get; set; }

    [Required]
    [Column("CHIP")]
    [StringLength(255)]
    public string Chip { get; set; }

    [Required]
    [Column("RAM")]
    [StringLength(255)]
    public string Ram { get; set; }

    [Required]
    [Column("ROM")]
    [StringLength(255)]
    public string Rom { get; set; }

    [Required]
    [Column("SIM")]
    [StringLength(255)]
    public string Sim { get; set; }

    [Required]
    [Column("BATTERY_CHARGER")]
    [StringLength(255)]
    public string BatteryCharger { get; set; }
}