// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("parameter_backupcharger")]
[Index("ProductId", Name = "FK_parameter_backupcharger_PRODUCT_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class ParameterBackupcharger
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Required]
    [Column("EFFICIENCY")]
    [StringLength(255)]
    public string Efficiency { get; set; }

    [Required]
    [Column("CAPACITY")]
    [StringLength(255)]
    public string Capacity { get; set; }

    [Required]
    [Column("TIMEFULLCHARGE")]
    [StringLength(255)]
    public string Timefullcharge { get; set; }

    [Required]
    [Column("INPUT")]
    [StringLength(255)]
    public string Input { get; set; }

    [Required]
    [Column("OUTPUT")]
    [StringLength(255)]
    public string Output { get; set; }

    [Required]
    [Column("CORE")]
    [StringLength(255)]
    public string Core { get; set; }

    [Required]
    [Column("TECH")]
    [StringLength(255)]
    public string Tech { get; set; }

    [Required]
    [Column("SIZE")]
    [StringLength(255)]
    public string Size { get; set; }

    [Required]
    [Column("WEIGHT")]
    [StringLength(255)]
    public string Weight { get; set; }

    [Required]
    [Column("MADEIN")]
    [StringLength(255)]
    public string Madein { get; set; }

    [Required]
    [Column("BRANDOF")]
    [StringLength(255)]
    public string Brandof { get; set; }

    [Required]
    [Column("BRAND")]
    [StringLength(255)]
    public string Brand { get; set; }

}