// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("product")]
[Index("Category", Name = "FK_product_CATEGORY")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class Product
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NAME")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("PRICE")]
    public double Price { get; set; }

    [Column("DESCRIPTION", TypeName = "text")]
    public string Description { get; set; }

    [Required]
    [Column("IMAGE", TypeName = "mediumblob")]
    public byte[] Image { get; set; }

    [Column("CATEGORY")]
    public int Category { get; set; }

    [Required]
    [Column("BRAND")]
    [StringLength(255)]
    public string Brand { get; set; }

    [Column("PRE_DISCOUNT")]
    public double PreDiscount { get; set; }

    [Column("DISCOUNT_PERCENT")]
    public double DiscountPercent { get; set; }
}