// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TechShopBackendDotnet.Models;

[Table("review")]
[Index("CustomerEmail", Name = "FK_review_CUSTOMER_EMAIL")]
[Index("ProductId", Name = "PRODUCT_ID")]
[MySqlCollation("utf8mb4_general_ci")]
public partial class Review
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Required]
    [Column("CUSTOMER_EMAIL")]
    public string CustomerEmail { get; set; }

    [Column("RATING")]
    public int Rating { get; set; }

    [Column("CONTENT", TypeName = "text")]
    public string Content { get; set; }

    [Column("ADMIN_REPLY", TypeName = "text")]
    public string AdminReply { get; set; }

    [Column("CREATED_AT", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("UPDATED_AT", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }
}